version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URL=mongodb://admin:89450@mongodb:27017/taskly?authSource=admin
      - JWT_ACCESS_SECRET=5f4dcc3b5aa765d61d8327deb882cf99
      - JWT_REFRESH_SECRET=5f4dcc3b32138092831d8327deb882cf99
      - FILES_SERVICE_URL=http://files-app:8080
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  files-app:
    build:
      context: ./files-service
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - MAIN_API=http://backend:3001
      - DATABASE_URL=postgresql://user:password@postgres:5432/times_files
    volumes:
      - ./files-service:/application
      - files_data:/application/files
    command: python server.py
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_PUBLIC_API_URL=http://localhost:3001/api/
      - NUXT_PUBLIC_FILES_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
